spring:          
 aop:
  auto: true 
  proxy-target-class: false
        
 messages:
  always-use-message-format: false 
  basename: messages 
  cache-seconds: -1 
  encoding: UTF-8  
  fallback-to-system-locale: true
 mvc:        
        dispatch-trace-request: false 
        dispatch-options-request: true               
        
 couchbase:
  bucket:
   name: default   
 datasource:
  url: jbdc:mysql://localhost:3306/mydb?useSSL=false
  username: root
  password: root
 jpa:
  show-sql:
          true
  hibernate:
           ddl-auto:
                   update
           naming:
             strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
            hibernate:
                     dialect: org.hibernate.dialect.MySQLSDialect
                                    
security:
        oauth2:
              resource:
                      prefer-token-info: true 
                      service-id: resource
                      
                      

                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  